using System;

namespace BulletXNA.BulletDynamics
{
	[Flags]
	public enum SolverMode
	{
		SOLVER_RANDMIZE_ORDER = 1,
		SOLVER_FRICTION_SEPARATE = 2,
		SOLVER_USE_WARMSTARTING = 4,
		SOLVER_USE_FRICTION_WARMSTARTING = 8,
		SOLVER_USE_2_FRICTION_DIRECTIONS = 0x10,
		SOLVER_ENABLE_FRICTION_DIRECTION_CACHING = 0x20,
		SOLVER_DISABLE_VELOCITY_DEPENDENT_FRICTION_DIRECTION = 0x40,
		SOLVER_CACHE_FRIENDLY = 0x80,
		SOLVER_SIMD = 0x100,
		SOLVER_CUDA = 0x200
	}
}
