namespace BulletXNA.BulletDynamics
{
	public enum TypedConstraintType
	{
		POINT2POINT_CONSTRAINT_TYPE = 3,
		HINGE_CONSTRAINT_TYPE = 4,
		CONETWIST_CONSTRAINT_TYPE = 5,
		D6_CONSTRAINT_TYPE = 6,
		SLIDER_CONSTRAINT_TYPE = 7,
		CONTACT_CONSTRAINT_TYPE = 8,
		D6_SPRING_CONSTRAINT_TYPE = 9,
		MAX_CONSTRAINT_TYPE = 10
	}
}
